# Workflow derived from https://github.com/posit-dev/setup-air/tree/main/examples

# name: format-suggest

on:
  workflow_call:

jobs:
  format-suggest:
    name: format-suggest
    runs-on: ubuntu-latest

    permissions:
      # Required to push suggestion comments to the PR
      pull-requests: write

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install
        uses: posit-dev/setup-air@cf390573ff4fe0f198f35df3a642b1409328d859 # v1
        with:
          version: 0.9.0

      - name: Format
        run: air format .

      - name: Suggest
        uses: reviewdog/action-suggester@6ba408415017b58ee944777db851caa3d2d451b7 # v1
        with:
          level: error
          fail_level: error
          tool_name: air
