on:
  workflow_call:

name: check-docs

jobs:
  check-link-rot:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Restrict to IndrajeetPatil repositories
        if: github.repository_owner != 'IndrajeetPatil'
        run: |
          echo "::error::This workflow is private and only available to repositories under IndrajeetPatil."
          exit 1

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411 # v2.8.0
        with:
          fail: true

  check-spelling:
    runs-on: ubuntu-latest

    steps:
      - name: Restrict to IndrajeetPatil repositories
        if: github.repository_owner != 'IndrajeetPatil'
        run: |
          echo "::error::This workflow is private and only available to repositories under IndrajeetPatil."
          exit 1

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Spell Checker
        uses: crate-ci/typos@bee27e3a4fd1ea2111cf90ab89cd076c870fce14 # v1.48.0
