# To understand the aim and scope of this workflow, have a look at these slides:
# https://indrajeetpatil.github.io/preventive-r-package-care/
on:
  workflow_call:

name: style

jobs:
  style:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-r@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2.11.4
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2.11.4
        with:
          dependencies: '"hard"'
          extra-packages: |
            local::.
            r-lib/pkgapi
            r-lib/styler
            anthonynorth/roxyglobals
          needs: |
            check

      - name: Enable styler cache
        run: |
          styler::cache_activate()
        shell: Rscript {0}

      - name: Determine cache location
        id: styler-location
        run: |
          cat(
            "location=",
            styler::cache_info(format = "tabular")$location,
            "\n",
            file = Sys.getenv("GITHUB_OUTPUT"),
            append = TRUE,
            sep = ""
          )
        shell: Rscript {0}

      - name: Cache styler
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ${{ steps.styler-location.outputs.location }}
          key: ${{ runner.os }}-styler-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-styler-
            ${{ runner.os }}-

      - name: Style package
        run: |
          options(crayon.enabled = TRUE)
          styler::style_pkg(filetype = c(".R", ".Rmd", ".Rmarkdown", ".Rnw"))
        shell: Rscript {0}

      - name: Check for style violations
        run: |
          GREEN='\033[0;32m'
          RED='\033[0;31m'
          if git diff --quiet; then
            echo -e "\n${GREEN}All files follow the style guide.\n"
          else
            echo -e "\n${RED}Some files don't follow the style guide. Run styler::style_pkg() with latest {styler}.\n"
            exit 1
          fi
